import Head from "next/head";
import {BsFillMoonStarsFill} from "react-icons/bs";
import {AiFillTwitterCircle, AiFillLinkedin, AiFillInstagram, AiFillGithub} from "react-icons/ai";
import Image from "next/image";
import avatar from "../public/avatar2.webp";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode? "dark": ""}>
      <Head>
        <title>Hatif Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-black">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-allura">Mohammad Hatif Osmani</h1>
            <ul className=" flex items-center">
              <li><a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="">Resume</a></li>
            </ul>
          </nav>
          <div className=" text-center p-10 items-center flex-col">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">Mohammad Hatif Osmani</h2>
            <h3 className="text-2xl py-2">Web-Developer and Data Science Enthusiast</h3>
            <p className="text-md py-5 leading-8 text-gray-800">Hi there! My name is Hatif and I am currently an ETCE undergrad in my freshman year at Jadavpur University, Kolkata.
            I have a diverse range of skills and interests. I love experimenting with ne technologies and learning new things.
            I am always looking for new opportunities to learn and grow, and I am driven by the multitudinous possibilities the my future holds.</p>
          </div>
          <div className=" text-5xl flex justify-center gap-16 py-3 text-gray-800">
            <AiFillInstagram/>
            <AiFillLinkedin/>
            <AiFillTwitterCircle/>
            <AiFillGithub/>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={avatar} alt="avatar" layout="fill" objectFit="cover"/>
          </div>
        </section>

        <section>
          <div>
            <h3 className=" text-3xl py-1">Services I offer</h3>
            <p className="text-md py-5 leading-8 text-gray-800" >I do remote work</p>
          </div>
          <div className="lg:flex gap-10">
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className=" flex justify-center"><Image src={code} alt="code" width={100} height={100} /></div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <h4 className="py-4 text-teal-600">Backend</h4>
              <p className="text-gray-800 py-1">Flask</p>
              <p className="text-gray-800 py-1">Django</p>
              <p className="text-gray-800 py-1">FastAPI</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">Node.js</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className=" flex justify-center"><Image src={code} alt="code" width={100} height={100} /></div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <h4 className="py-4 text-teal-600">Frontend</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Tailwind</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Next</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <div className=" flex justify-center"><Image src={code} alt="code" width={100} height={100} /></div>
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <h4 className="py-4 text-teal-600">Data Science</h4>
              <p className="text-gray-800 py-1">Numpy</p>
              <p className="text-gray-800 py-1">Pandas</p>
              <p className="text-gray-800 py-1">Scikit-Learn</p>
              <p className="text-gray-800 py-1">Tensorflow</p>
            </div>
          </div>
        </section>
        <section class="bg-white dark:bg-gray-900">
          <div class="py-8 lg:py-16 px-4 mx-auto max-w-screen-md">
              <h2 class="mb-4 text-4xl tracking-tight font-extrabold text-center text-gray-900 dark:text-white">Contact Us</h2>
              <p class="mb-8 lg:mb-16 font-light text-center text-gray-500 dark:text-gray-400 sm:text-xl">Got a technical issue? Want to send feedback about a beta feature? Need details about our Business plan? Let us know.</p>
              <form action="mailto:md.hatifosmani15@gmail.com" method="post" enctype="text/plain" class="space-y-8">
                  <div>
                      <label for="email" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Your email</label>
                      <input type="email" id="email" class="shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="abc@xyz.com" required/>
                  </div>
                  <div>
                      <label for="subject" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-300">Subject</label>
                      <input type="text" id="subject" class="block p-3 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 shadow-sm focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 dark:shadow-sm-light" placeholder="Let me know how I can help you" required/>
                  </div>
                  <div class="sm:col-span-2">
                      <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your message</label>
                      <textarea id="message" rows="6" class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg shadow-sm border border-gray-300 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Leave a comment..."></textarea>
                  </div>
                  <button type="submit" class="py-3 px-5 text-sm font-medium text-center text-white rounded-lg bg-primary-700 sm:w-fit hover:bg-primary-800 focus:ring-4 focus:outline-none focus:ring-primary-300 dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800" value="send">Send message</button>
              </form>
          </div>
        </section>
      </main>
    </div>
  ) 
}
